org: lvaladares
app: tsdaas-demo-service
service: tsdaas-demo-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-sam

package:
  exclude:
    - .git/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: src/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any

custom:
  optimize:
    external: ['swagger-ui-dist']

  webpack:
    webpackConfig: './webpack-config.js'
    includeModules: true
    packager: 'npm'
    excludeRegex: .e2e-spec|.map|test
